# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=b'media', verbose_name='Profile Picture'),
        ),
    ]
