# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170503_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile', verbose_name='Profile Picture'),
        ),
    ]
